### ISSUE TITLE
Remove `remove_attribute` function from Renderer interface

### ISSUE THREAD

**Issue by berendkleinhaneveld** [fork-tongue/collagraph#12]
The longer we stare at it, the more it doesn't seem to make any sense for any of our purposes. Maybe `set_attribute` might benefit from a rename to something like: `update_attribute` or `patch_attribute`.

**Comment by berendkleinhaneveld** [comment]
```python
        # Remove old properties
        for key in prev_props:
            # Is key an actual property?
            if not is_property(key):
                continue
            # Is key gone?
            if key in next_props:
                continue

            self.renderer.remove_attribute(dom, key, prev_props[key])
```
Still a bit unsure what to do here: should we just call: `self.renderer.set_attribute(dom, key, None)`? Or should we just consider not supporting the removal of attributes at all? In that case we could just remove this piece of code. I'm leaning towards the latter.

**Comment by Korijn** [comment]
* Do you have any examples of situations where this code path would end up being called?
* If so, what would be the preferred behavior? You could also just raise an error, saying you don't support it.

**Comment by berendkleinhaneveld** [comment]
> * Do you have any examples of situations where this code path would end up being called?

Only a contrived example currently in the test suite :/

I think I'll just raise an error for now (thanks for the suggestion!) and we'll see how many times we run into it.

**Comment by berendkleinhaneveld** [comment]
Actually: I'm not going to touch this. It should be up to the renderer to decide whether to implement support for this.
