### ISSUE TITLE
Issue with reactivity when adjusting elements of reactive collections

### ISSUE THREAD

**Issue by berendkleinhaneveld** [fork-tongue/collagraph#16]
When an element of a reactive collection (list or dict) is adjusted, the change isn't picked up in the `update_dom` function, so the change is never rendered to the actual DOM.

**Comment by Korijn** [comment]
In vue.js (v3) a component's props are copied via `toRaw` which implicitly creates a deep copy, so we can do the same in collagraph.

Reference: https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-core/src/componentProps.ts#L205
