### ISSUE TITLE
fiber.component in lambda can sometimes resolve to None

### ISSUE THREAD

**Issue by berendkleinhaneveld** [fork-tongue/collagraph#17]
When generating lots of events / changes, it might happen that `fiber.component` in the `fiber.component_watcher` might resolve to `None`.

**Comment by Korijn** [comment]
In vue.js (v3) a component's props are copied via `toRaw` which implicitly creates a deep copy, so we can do the same in collagraph.

Reference: https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-core/src/componentProps.ts#L205

**Comment by Korijn** [comment]
I wonder if this has been fixed by https://github.com/fork-tongue/observ/pull/71 ?

**Comment by berendkleinhaneveld** [comment]
I actually don't think so, as apparently the watcher is fired because else we wouldn't see the error at all. I guess we need to reproduce the actual error in order to verify whether this is still a problem or not.
