### ISSUE TITLE
Find out how to debug code in cgx files

### ISSUE THREAD

**Issue by berendkleinhaneveld** [fork-tongue/collagraph#35]

**Comment by ivoflipse** [comment]
I don't yet know how, but at least this does not work:
![2022-05-10 16_25_52-cgx_component_example cgx - collagraph - Visual Studio Code](https://user-images.githubusercontent.com/485186/168034293-b9617165-b8af-40a9-b670-e9d103e5a1c2.png)

I imagine the AST parsing just removes it entirely
