### ISSUE TITLE
DomRenderer skips certain tags

### ISSUE THREAD

**Issue by ivoflipse** [fork-tongue/collagraph#67]
Given the following snippet:
``` 
<div class="select">
    <select>
      <option>A</option>
      <option>B</option>
      <option>C</option>
    </select>
  </div>
```
which renders as follows:
![image](https://user-images.githubusercontent.com/485186/175553616-fedb830a-ed93-4c35-8eb7-951386170cf5.png)
![image](https://user-images.githubusercontent.com/485186/175553808-c61cdfad-8a1e-4c8c-9ee1-4a57b5d2621d.png)

If I put the snippet inside a <template> tag in a cgx file it renders like this:
![image](https://user-images.githubusercontent.com/485186/175553679-5e8217b1-de2c-4ce6-9b1b-b66063610fd5.png)
![image](https://user-images.githubusercontent.com/485186/175553739-3e84465f-4757-4ca6-9e19-1410342b00bd.png)

The select tag is somehow skipped. Any ideas on what could be causing this?

**Comment by berendkleinhaneveld** [comment]
Wow: apparently, an (empty) `<select>` dom element is a 'Falsey' object, so checks like: `if fiber.dom` don't work as expected... Fix upcoming in the `dom-renderer` branch.

**Comment by Korijn** [comment]
> Wow: apparently, an (empty) `<select>` dom element is a 'Falsey' object, so checks like: `if fiber.dom` don't work as expected... Fix upcoming in the `dom-renderer` branch.

Can't you implement `__bool__` on VNode or Fiber? Or is `fiber.dom` an actual browser Element? In that case... I see this in my console:

![image](https://user-images.githubusercontent.com/1882046/176177289-cbf7a721-7e67-4ec3-869b-a9dc291e133f.png)

You might also prefer to stick with what you already committed now. I'm just proposing this as an alternative.

**Comment by berendkleinhaneveld** [comment]
The `fiber.dom` is a javascript object wrapped in Python. So I think that there might be something going on in the Python wrapper which makes the select element evaluate to `False`.
